### ISSUE TITLE
Plain text files not interpreted as Unicode

### ISSUE THREAD

**Issue by joelmeyerhamme** [nextcloud/ios#13]
When uploading a plain text file encoded as Utf8 to a Next Cloud instance and opening it in the app, it gets partially unreadable. 

The default encoding for text files should be Utf8.

**Comment by marinofaggiana** [comment]
please @joelmeyerhamme   attachment a example test file.

**Comment by joelmeyerhamme** [comment]
The attached Utf8 encoded file containing `ä` gets interpreted as `Ã¤` in ISO Latin 1.
[test.txt](https://github.com/nextcloud/ios/files/654418/test.txt)

**Comment by marinofaggiana** [comment]
i see : 
![2016-12-15 17-04-13 3154](https://cloud.githubusercontent.com/assets/8616947/21231497/bf18973e-c2e8-11e6-9afa-0d0143a86309.png)

**Comment by joelmeyerhamme** [comment]
The bug appears to be specific to the .md file ending for Markdown. Haven't thought of that, sorry for not including it in the initial comment.

**Comment by marinofaggiana** [comment]
oh Yes, true.

**Comment by rakekniven** [comment]
Did some tests.

Created three textfiles. Their names should explain everything. You will see screenshots for each file as well.

[test-utf8-wo-bom.txt](https://github.com/nextcloud/ios/files/892171/test-utf8-wo-bom.txt)  [test-utf8-ansi.txt](https://github.com/nextcloud/ios/files/892173/test-utf8-ansi.txt) [test-utf8-w-bom.txt](https://github.com/nextcloud/ios/files/892172/test-utf8-w-bom.txt)

OK
![2017-04-04 08-19-48 6185](https://cloud.githubusercontent.com/assets/2069590/24643691/d8778e06-190f-11e7-835b-01bdb29fb689.jpg)

OK
![2017-04-04 08-19-54 6186](https://cloud.githubusercontent.com/assets/2069590/24643692/d87aac62-190f-11e7-9ce4-2822d2b5282b.jpg)

The UTF-8 file withoud BOM fails.
![2017-04-04 08-19-59 6187](https://cloud.githubusercontent.com/assets/2069590/24643690/d8776070-190f-11e7-966f-e312832681e5.jpg)

**Comment by KeiOtori** [comment]
I have the same issue here: after opening file content in UTF-8, viewer looks weird. 
But i can copy broken text, and paste it into other app - there i see it in correct form.

Here is my example:
- What i was supposed to see:
![default](https://user-images.githubusercontent.com/14834366/28563237-05c11186-712e-11e7-8baa-12a4c705d854.png)

- What i really see:
![2017-07-25 11-32-11-1](https://user-images.githubusercontent.com/14834366/28563294-32df0d58-712e-11e7-9b48-2380772e2a50.PNG)

My test file is attached, it is encoded in UTF-8, but in iOS app it is misinterpreted as Windows-1252 / CP-1252 (??)
[TestingEncoding.txt](https://github.com/nextcloud/ios/files/1172532/TestingEncoding.txt)

**Comment by marinofaggiana** [comment]
Thanks @KeiOtori I make a test

**Comment by marinofaggiana** [comment]
fixed.

**Comment by rakekniven** [comment]
@marinofaggiana This is working AFAICS, or?

**Comment by marinofaggiana** [comment]
yes.

**Comment by binss** [comment]
@marinofaggiana I still have this issue when I open the markdown(.md) file, but txt file display well

I have file test.md with content:

```
你好
こんにちは
hello
```

It seem wrong as md file:

![img_248535134340-1](https://user-images.githubusercontent.com/5955698/40575874-aac56c9a-611f-11e8-9722-d425e4273050.jpeg)

but well as txt file 

![img_ae44e2b432ba-1](https://user-images.githubusercontent.com/5955698/40575883-cc9cc0c0-611f-11e8-84bb-8004119c44a8.jpeg)

**Comment by rakekniven** [comment]
The issues is about plain text files with file extension txt.
Could you please try to copy your file and change extension md to txt and give some feedback?

**Comment by binss** [comment]
When I change extension to txt, it shows correctly. I guess it maybe a decode problem for md extension file with plain text.

**Comment by marinofaggiana** [comment]
@binss try with the next beta 2.21.0.00016
