### ISSUE TITLE
auto upload created and modified date get set to upload date/time

### ISSUE THREAD

**Issue by tzapu** [nextcloud/ios#256]
while manual upload seems to preserve created and modified

for me at least it would feel natural to have auto upload preserve dates as well

cheers

**Comment by marinofaggiana** [comment]
Hi @tzapu  ... where is the issue ? I don't understand

**Comment by tzapu** [comment]
hi,
i would expect all my files to keep their created and modified time/date
it messes up all file views based on created/modified, it also seems really odd that some upload methods preserve those file attributes while others change them..
also, most of my files appear under today in the ios app after being uploaded, although they strech a few years. seems non intuitive at all.

**Comment by tzapu** [comment]
hello,

will this be considered or how it is now is how it will remain?

cheers

**Comment by tzapu** [comment]
@marinofaggiana any chance you could chime in on this? sorry to keep pestering you about it, but at least to me it is something that stops me uploading all the family pics

thank you very much for everything

**Comment by tzapu** [comment]
<img width="854" alt="screenshot 2017-06-29 14 47 30" src="https://user-images.githubusercontent.com/2983312/27686127-0818c8ce-5cda-11e7-8379-c0b9262ef691.png">

a 2012 photo should really not show up as created today

**Comment by marinofaggiana** [comment]
mmm .. @jancborchardt .. for you ? now the file name is detect from creationDate of record on Photo, this date derive from EXIF or iOS creation on your memory ...

**Comment by tzapu** [comment]
a couple of examples:
- dropbox camera upload for instance preserves created/modified 
- macOS Image Capture app preserves dates

**Comment by marinofaggiana** [comment]
as we (preserve on FileName)

**Comment by tzapu** [comment]
yes, filenam is ok, but dropbox and all preserve mtime and ctime as well

<img width="640" alt="screenshot 2017-06-29 16 14 32" src="https://user-images.githubusercontent.com/2983312/27689183-11018974-5ce6-11e7-9d35-8dd5965ab711.png">

which makes sense to me 
thanks

**Comment by marinofaggiana** [comment]
sorry but this is not a iOS problem ...

**Comment by mario** [comment]
You can set last modified time however ...

**Comment by tzapu** [comment]
@marinofaggiana should i report this to main nextcloud repo then? thanks
@mario i m not sure i understand what i need to do

**Comment by mario** [comment]
@tzapu was talking to @marinofaggiana :)

**Comment by tzapu** [comment]
guys, sorry to keep pushing this
is it being considered? do i need to post it somewhere else? what do i need to do to make this happen?
am i flogging a dead horse? 😄 

cheers

**Comment by enoch85** [comment]
https://github.com/nextcloud/ios/issues/313 Related.

**Comment by yamlfd** [comment]
The issue seems only half fixed. I have seen all images seem to habe the correct date, but all mp4 files have the upload date. Client is 2.17.5 on iphone.

**Comment by tzapu** [comment]
i've just tried again with 1.17.6.00008 and modified/created are still set to current time/date

**Comment by binarybucks** [comment]
Same issue here  I've been using version 2.18.0 over a longer period (e.g. vacation) without internet access. Once the device was back to a location with Wifi all files were uploaded and named with the current date. Hence, all photos are now named incorrectly and completely out of order. 

Files uploaded should be named after the date taken. I don't see case were the upload date is of any relevance.

**Comment by marinofaggiana** [comment]
@binarybucks the filename take the creationDate of Asset ... why is incorrectly ?

**Comment by mario** [comment]
@marinofaggiana can you tell me where uploads happen? I can fix this, at least for mtime and ctime preservation.

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/blob/afc87ce348c5217e8306c17ed1702544a6c91121/iOSClient/AutoUpload/NCAutoUpload.m#L383

**Comment by mario** [comment]
@marinofaggiana I don't care much about this. What I'm asking is where is the PUT method for uploading the file itself? I need to set a header then the MTime will be preserved. Also, for filedate I'd use modifiedDate since creationDate isn't always reliable.

**Comment by marinofaggiana** [comment]
hahah moment ! and this is the put for URLSession Upload

https://github.com/nextcloud/ios/blob/afc87ce348c5217e8306c17ed1702544a6c91121/iOSClient/Networking/CCNetworking.m#L1245

**Comment by mario** [comment]
@marinofaggiana fix could be here, please test :)

https://github.com/nextcloud/ios/pull/388

**Comment by yamlfd** [comment]
The question is more, why are you changing the file name from iphone. Why not uploading as is? Date is inside meta data and the file date should also be correct. Renaming the file is not needed.

**Comment by binarybucks** [comment]
@marinofaggiana you're right, they're indeed named correctly after the date they were taken. The gallery view in the app just sorted them wrong.

**Comment by marinofaggiana** [comment]
ok @mario  the Header works but remember : 

long dateFileCreation = [asset.creationDate timeIntervalSince1970];

witkout * 1000

Thanks

**Comment by LuckyLuke75** [comment]
Pleaaase merge this, I’m switching from Dropbox and this issue is a big no-go for me and I think other people too :(

**Comment by marinofaggiana** [comment]
@LuckyLuke75 this issue is already fixed....

**Comment by tzapu** [comment]
hi, in what version, last i tested, some time ago using the beta version in october, it wasn't ...

**Comment by LuckyLuke75** [comment]
@marinofaggiana Any update ?

**Comment by marinofaggiana** [comment]
2.19.1

**Comment by LuckyLuke75** [comment]
I've checked 2.19.3 and the bug is still here, maybe it was reintroduced in 2.19.2 ?
@rakekniven could you check this one maybe ?

**Comment by invario** [comment]
Android v 3.12.1 RC1 and this is happening with files in my Auto upload.

**Comment by johkoenig** [comment]
This bug is still present in v3.0.7 and it is pretty annoying. Are there any steps planned to fix this soon? I just uploaded 3000 images and the image order on the nextcloud web interface is completely messed up.

**Comment by pysiak** [comment]
Hi, I'm using Nextcloud Liquid for iOS 4.0.6.0 @ 2021 and Nextcloud Server 22.1.1 and I have the same.
I enabled photo upload and it uploads photos from a time span of multiple years from my phone, but they seem to get the date of the moment I upload. So of course it makes sense to upload fresh photos this way, but photos from 2016 shouldn't come up as September 22nd.

**Comment by sidequestboy** [comment]
I’m using Nextcloud iOS 7.0.7 with nextcloud aio server 31.0.7 and I am running into this issue. The file names contain the correct date information, but many of the photos get sorted to “Today” in the Media tab view.

**Comment by rakekniven** [comment]
This issue did not had any comments for four years... Do not wake the dead.
