### ISSUE TITLE
Favorite folders do not show in normal files view and are empty in favorite file view until manual refresh

### ISSUE THREAD

**Issue by khlschrnk** [nextcloud/ios#266]
Nextcloud for iOS 2.17.3.00009
Nextcloud Server 12.0.0
This problem exists since I startet to use the favorite functionality on the iOS app, also with server version 11.0.3.

I got a folder that is shared with one other nextcloud user. This folder contains 33 folders and 6 files with a size of 7.33 GB
This folder is listed in the files view in the iOS app. When I scroll down I see "31 folders, 6 files, 7.33 GB". There are 2 folders missing, I also can't find them in the list. When I click on favorites view in the iOS app it does show the 2 missing folders. If I open them they appear to be empty ("Noch keine Favoriten vorhanden"). But in fact the contain each more than 10 files.
When I go back to the normal files view and refresh the folder (the one that has 2 folders missing) the missing folders suddenly appear. On the very bottom it now states the correct number of folders and files (33 folders, 6 files, 7.33 GB).
When I now go to favorites view again I can still see my 2 favorite folders. When I enter them I now also can see its contents.
If I remove the favorite flag from the folders they always appear in the normal file list.

My expectations:
I use the favorite tag to keep my files available for offline use (mostly pictures). So I expect to have favorite folders downloaded and available in the iOS at all time. I also expect them to be kept up to date.

**Comment by rakekniven** [comment]
Would you like to participate on Testflight programm and see if your issue is already solved? For details see #260

**Comment by khlschrnk** [comment]
My issue is solved in 2.17.4.00008.

**Comment by rakekniven** [comment]
Ok, so I will close it

**Comment by khlschrnk** [comment]
I just updated to testflight version 2.17.4 (14).
For testing I did reset the app and found the issue to be back partly.

After setting up a new server connection the favorites are empty. (Please note that my favorites are not the root folders). Only after switching to normal files view and opening the folder that contains the favorites they start to appear in favorites file view.

I also only have folders as favorites. After having them visible in favorites view they still do not contain any files in this favorites view. I also have to manually load the contents (by just entering the folders in normal file view) to see all of the files in favorites file view.

This problem did actually not exist with this version and now only happens because I did reset the application. I also tried to remove and reinstall the app.

**Comment by khlschrnk** [comment]
I just tested the bahavior with 2.17.4(20).

It is still the same as before. When I reset the application and set up a new cloud account the favorites are empty. They start to appear only after I have opened the respective parent directory in normal files view.

Also the favorites (I only have folders as favorites) do not contain any files in favorites file view until I have opened the respective favorite directory in normal files view.

I would expect that the app does scan for any favorites files and folders and also loads the content of these folders on any startup.

**Comment by jonathanpantall** [comment]
I've noticed this behavior whenever upgrading to a newer version of the iOS client. For example, updating from an older version to 2.20.5 will cause this to happen.

Manually refreshing will allow the folder and file names to appear in the table (screenshot #1). When viewing favorited items via the Favorites tab, files aren't viewable unless you manually refresh and restart the app (screenshot #2).

<img width="322" alt="screen shot 2018-03-19 at 8 23 18 am" src="https://user-images.githubusercontent.com/25255725/37598292-d1fe11a0-2b4f-11e8-983d-5b576115d65a.png">

<img width="320" alt="screen shot 2018-03-19 at 8 20 44 am" src="https://user-images.githubusercontent.com/25255725/37598293-d20d2b86-2b4f-11e8-9845-ef23a98f0866.png">

Thanks for helping diagnose this tricky bug and let me know if there's anything I can do to help.

**Comment by khlschrnk** [comment]
I also see this behaviour again. I can't tell when but with version 2.20.7.00003 I need to manually refresh any favorite folder to see the files below.
Also reseeting the app does not solve this problem.

**Comment by khlschrnk** [comment]
I would like to highlight this as it‘s still the same in 2.21. (18).

**Comment by marinofaggiana** [comment]
@khlschrnk  try with 2.20.0 Build 17 please
